# Generated by Django 2.1.7 on 2019-03-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190315_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='movie',
            new_name='movie_id',
        ),
    ]
